# Copyright (C) 2026 olvwm.xview@gmail.com
# SPDX-License-Identifier: GPL-3.0-only

lib_LTLIBRARIES = libxview.la

libxview_la_LDFLAGS = -version-number 3:2:4

libxview_la_SOURCES = \
	attr/attr.c \
	attr/attr_copy.c \
	attr/attr_cu.c \
	attr/attr_cust.c \
	attr/attr_util.c \
	base/base_data.c \
	base/drawable.c \
	base/generic.c \
	base/xv.c \
	base/xv_debug.c \
	base/xv_error.c \
	base/xv_init.c \
	base/xv_init_x.c \
	base/xv_list.c \
	base/xv_parse.c \
	base/xv_usage.c \
	canvas/canvas.c \
	canvas/cnvs_cb.c \
	canvas/cnvs_data.c \
	canvas/cnvs_get.c \
	canvas/cnvs_input.c \
	canvas/cnvs_resze.c \
	canvas/cnvs_scrol.c \
	canvas/cnvs_set.c \
	canvas/cnvs_view.c \
	color/cms.c \
	color/cms_data.c \
	color/cms_pblc.c \
	cursor/cur_rodata.c \
	cursor/curs_cmpat.c \
	cursor/curs_data.c \
	cursor/cursor.c \
	cursor/curs_pri.c \
	defaults/defaults.c \
	dnd/dnd.c \
	dnd/dnd_data.c \
	dnd/dnd_decode.c \
	dnd/dnd_dsdm.c \
	dnd/dnd_pblc.c \
	dnd/dndutil.c \
	dnd/site.c \
	dnd/site_data.c \
	dnd/site_pblc.c \
	file_chooser/fchsr_data.c \
	file_chooser/fc_layout.c \
	file_chooser/file_chsr.c \
	file_chooser/file_list.c \
	file_chooser/flist_data.c \
	file_chooser/hist_data.c \
	file_chooser/hist_list.c \
	file_chooser/hist_menu.c \
	file_chooser/path.c \
	file_chooser/path_data.c \
	file_chooser/xv_path_util.c \
	filter/filter.c \
	font/font.c \
	font/font_data.c \
	font/font_get.c \
	font/font_set.c \
	font/font_x.c \
	font/pf.c \
	font/pf_text.c \
	font/pf_ttext.c \
	frame/fm_bdry.c \
	frame/fmbs_dsty.c \
	frame/fmbs_get.c \
	frame/fmbs_set.c \
	frame/fmcmd_dsty.c \
	frame/fmcmd_get.c \
	frame/fm_cmdline.c \
	frame/fmcmd_set.c \
	frame/fm_data.c \
	frame/fm_destroy.c \
	frame/fm_display.c \
	frame/fm_geom.c \
	frame/fm_get.c \
	frame/fmhlp_dsty.c \
	frame/fmhlp_get.c \
	frame/fmhlp_set.c \
	frame/fm_input.c \
	frame/fm_layout.c \
	frame/fm_rescale.c \
	frame/fm_rodata.c \
	frame/fm_set.c \
	frame/fm_win.c \
	frame/fm_xutil.c \
	frame/frame_base.c \
	frame/frame.c \
	frame/frame_cmd.c \
	frame/frame_help.c \
	frame/frame_init.c \
	frame/frame_sw.c \
	fullscreen/fs.c \
	fullscreen/fs_compat.c \
	fullscreen/fs_data.c \
	fullscreen/fs_get.c \
	fullscreen/fs_set.c \
	help/help.c \
	help/help_file.c \
	help/hlp_rodata.c \
	icon/icon.c \
	icon/icon_data.c \
	icon/icon_input.c \
	icon/icon_load.c \
	icon/icon_obj.c \
	io_stream/file_strms.c \
	io_stream/input.c \
	io_stream/io.c \
	io_stream/othr_strms.c \
	io_stream/output.c \
	io_stream/str_strms.c \
	menu/om_compat.c \
	menu/om_data.c \
	menu/om_get.c \
	menu/omi.c \
	menu/om_public.c \
	menu/om_render.c \
	menu/om_set.c \
	misc/bitmask.c \
	misc/convdup.c \
	misc/db_conv.c \
	misc/demorandom.c \
	misc/drop.c \
	misc/expandname.c \
	misc/expandpath.c \
	misc/getlogindr.c \
	misc/gettext.c \
	misc/hashfn.c \
	misc/quark.c \
	misc/setlocale.c \
	misc/windowloop.c \
	misc/xv_casecmp.c \
	misc/xv_deaf.c \
	misc/xv_i18n.c \
	misc/xv_icccm.c \
	misc/xv_path.c \
	misc/xv_util.c \
	misc/xv_version.c \
	misc/xv_win_lp.c \
	notice/notice.c \
	notice/notice_data.c \
	notice/notice_dstry.c \
	notice/notice_get.c \
	notice/notice_itm.c \
	notice/notice_ol.c \
	notice/notice_pt.c \
	notice/notice_set.c \
	notify/linux_select.c \
	notify/ndet_auto.c \
	notify/ndet_death.c \
	notify/ndet_die.c \
	notify/ndet_dodis.c \
	notify/ndet_event.c \
	notify/ndet_fcntl.c \
	notify/ndet_fd.c \
	notify/ndetgdeath.c \
	notify/ndetgetfnc.c \
	notify/ndetgevent.c \
	notify/ndetgexcep.c \
	notify/ndet_g_fd.c \
	notify/ndet_g_fds.c \
	notify/ndet_g_in.c \
	notify/ndetgitimr.c \
	notify/ndet_g_out.c \
	notify/ndet_g_pri.c \
	notify/ndet_g_sig.c \
	notify/ndetg_wait.c \
	notify/ndetitimer.c \
	notify/ndet_loop.c \
	notify/ndet_nodis.c \
	notify/ndetpdeath.c \
	notify/ndetpevent.c \
	notify/ndetpoll.c \
	notify/ndet_read.c \
	notify/ndetremove.c \
	notify/ndetsdeath.c \
	notify/ndetselect.c \
	notify/ndetsevent.c \
	notify/ndetsexcep.c \
	notify/ndet_s_fd.c \
	notify/ndet_sig.c \
	notify/ndet_s_in.c \
	notify/ndetsingle.c \
	notify/ndetsitimr.c \
	notify/ndet_s_out.c \
	notify/ndet_s_poll.c \
	notify/ndet_s_pri.c \
	notify/ndet_s_sig.c \
	notify/ndets_wait.c \
	notify/ndet_value.c \
	notify/ndet_veto.c \
	notify/ndet_wait.c \
	notify/ndisdispch.c \
	notify/ndis_d_pri.c \
	notify/ndisdsched.c \
	notify/ndisd_wait.c \
	notify/ndisgsched.c \
	notify/ndisssched.c \
	notify/nint_copy.c \
	notify/nint_get.c \
	notify/nintideath.c \
	notify/nintievent.c \
	notify/nintiexcpt.c \
	notify/nint_i_fd.c \
	notify/nint_i_fds.c \
	notify/nint_i_in.c \
	notify/nintiitimr.c \
	notify/nint_inter.c \
	notify/nint_i_out.c \
	notify/nint_i_sig.c \
	notify/ninti_wait.c \
	notify/nintndeath.c \
	notify/nintnevent.c \
	notify/nintnexcpt.c \
	notify/nint_next.c \
	notify/nint_n_fd.c \
	notify/nint_n_fds.c \
	notify/nint_n_in.c \
	notify/nintnitimr.c \
	notify/nint_n_out.c \
	notify/nint_n_sig.c \
	notify/nintn_wait.c \
	notify/nintrdeath.c \
	notify/nintremove.c \
	notify/nintrevent.c \
	notify/nintrexcpt.c \
	notify/nint_r_fd.c \
	notify/nint_r_fds.c \
	notify/nint_r_in.c \
	notify/nintritimr.c \
	notify/nint_r_out.c \
	notify/nint_r_sig.c \
	notify/nintr_wait.c \
	notify/nint_set.c \
	notify/nint_stack.c \
	notify/notifydata.c \
	notify/ntfyclient.c \
	notify/ntfy_cond.c \
	notify/ntfy_ctbl.c \
	notify/ntfy_debug.c \
	notify/ntfy_dump.c \
	notify/ntfy_fd_op.c \
	notify/ntfy_list.c \
	notify/ntfy_node.c \
	notify/ntfyperror.c \
	notify/ntfyprotec.c \
	notify/sys_fcntl.c \
	notify/sys_read.c \
	notify/sys_select.c \
	openwin/openwin.c \
	openwin/ow_data.c \
	openwin/ow_evt.c \
	openwin/ow_get.c \
	openwin/ow_paint.c \
	openwin/ow_rescale.c \
	openwin/ow_resize.c \
	openwin/ow_seln.c \
	openwin/ow_set.c \
	openwin/ow_view.c \
	panel/item.c \
	panel/item_data.c \
	panel/item_get.c \
	panel/item_set.c \
	panel/p_amb_data.c \
	panel/p_ambtn.c \
	panel/panel.c \
	panel/panel_data.c \
	panel/p_btn.c \
	panel/p_btn_data.c \
	panel/p_chcedata.c \
	panel/p_choice.c \
	panel/p_compat.c \
	panel/p_drop.c \
	panel/p_drp_data.c \
	panel/p_event.c \
	panel/p_gauge.c \
	panel/p_get.c \
	panel/p_image.c \
	panel/p_imcb.c \
	panel/p_list2.c \
	panel/p_list.c \
	panel/p_lst_data.c \
	panel/p_mlinetxt.c \
	panel/p_mltxdata.c \
	panel/p_msg.c \
	panel/p_msg_data.c \
	panel/p_ntx_data.c \
	panel/p_num_txt.c \
	panel/p_paint.c \
	panel/p_public.c \
	panel/p_scroll.c \
	panel/p_select.c \
	panel/p_set.c \
	panel/p_slider.c \
	panel/p_txt.c \
	panel/p_txt_data.c \
	panel/p_utl.c \
	panel/p_utl_data.c \
	panel/p_view.c \
	pw/mem.c \
	pw/mem_ops.c \
	pw/pw_batch.c \
	pw/pw_btchrop.c \
	pw/pw_cms.c \
	pw/pw_copy.c \
	pw/pw_get.c \
	pw/pw_line.c \
	pw/pw_plygon2.c \
	pw/pw_plyline.c \
	pw/pw_plypt.c \
	pw/pw_put.c \
	pw/pw_read.c \
	pw/pw_rotcmap.c \
	pw/pw_traprop.c \
	pw/pw_vector.c \
	pw/xv_bridge.c \
	pw/xv_olgx.c \
	pw/xv_rop.c \
	pw/xv_stencil.c \
	pw/xv_text.c \
	rect/rect.c \
	rect/rect_data.c \
	rect/rectlist.c \
	rect/rect_util.c \
	screen/screen.c \
	screen/scrn_cms.c \
	screen/scrn_data.c \
	screen/scrn_get.c \
	screen/scrn_lyout.c \
	screen/scrn_vis.c \
	scrollbar/sb.c \
	scrollbar/sb_compat.c \
	scrollbar/sb_data.c \
	scrollbar/sb_destroy.c \
	scrollbar/sb_event.c \
	scrollbar/sb_get.c \
	scrollbar/sb_paint.c \
	scrollbar/sb_pos.c \
	scrollbar/sb_scroll.c \
	scrollbar/sb_set.c \
	selection/sel_data.c \
	selection/selection.c \
	selection/sel_item.c \
	selection/sel_own.c \
	selection/sel_req.c \
	selection/sel_util.c \
	sel/sel_agent.c \
	sel/sel_appl.c \
	sel/sel_clnt.c \
	sel/sel_common.c \
	sel/sel_compat.c \
	sel/seln.c \
	sel/seln_data.c \
	sel/sel_policy.c \
	server_image/svrim_data.c \
	server_image/svrim_ops.c \
	server_image/svrim_pblc.c \
	server/server.c \
	server/svr_atom.c \
	server/svr_data.c \
	server/svr_get.c \
	server/svr_parse.c \
	server/svr_rodata.c \
	server/svr_set.c \
	server/svr_x.c \
	string_utils/str_utils.c \
	string_utils/whitespace.c \
	textsw/ei_attr.c \
	textsw/ei_text.c \
	textsw/es_attr.c \
	textsw/es_cp_file.c \
	textsw/es_file.c \
	textsw/es_mem.c \
	textsw/es_util.c \
	textsw/ev_attr.c \
	textsw/ev_display.c \
	textsw/ev_edit.c \
	textsw/ev_field.c \
	textsw/ev_once.c \
	textsw/ev_op_bdry.c \
	textsw/ev_update.c \
	textsw/finger_tbl.c \
	textsw/ps_impl.c \
	textsw/text.c \
	textsw/txt_again.c \
	textsw/txt_attr.c \
	textsw/txt_caret.c \
	textsw/txt_cb.c \
	textsw/txt_data.c \
	textsw/txt_dbx.c \
	textsw/txt_disp.c \
	textsw/txt_edit.c \
	textsw/txt_e_menu.c \
	textsw/txt_event.c \
	textsw/txt_field.c \
	textsw/txt_file.c \
	textsw/txt_filter.c \
	textsw/txt_find.c \
	textsw/txt_getkey.c \
	textsw/txt_incl.c \
	textsw/txt_input.c \
	textsw/txt_line.c \
	textsw/txt_load.c \
	textsw/txt_match.c \
	textsw/txt_menu.c \
	textsw/txt_move.c \
	textsw/txt_once.c \
	textsw/txt_popup.c \
	textsw/txt_putkey.c \
	textsw/txt_scroll.c \
	textsw/txt_search.c \
	textsw/txt_sel.c \
	textsw/txt_selsvc.c \
	textsw/txt_store.c \
	textsw/txt_tool.c \
	textsw/txt_view.c \
	ttysw/cim_change.c \
	ttysw/cim_size.c \
	ttysw/csr_change.c \
	ttysw/csr_init.c \
	ttysw/term_data.c \
	ttysw/term_ntfy.c \
	ttysw/termsw.c \
	ttysw/ttyansi.c \
	ttysw/tty.c \
	ttysw/tty_cb.c \
	ttysw/tty_compat.c \
	ttysw/tty_data.c \
	ttysw/tty_es.c \
	ttysw/tty_gtty.c \
	ttysw/tty_init.c \
	ttysw/tty_main.c \
	ttysw/tty_mapkey.c \
	ttysw/tty_menu.c \
	ttysw/tty_modes.c \
	ttysw/tty_newtxt.c \
	ttysw/tty_ntfy.c \
	ttysw/ttyselect.c \
	ttysw/tty_stty.c \
	ttysw/ttytl.c \
	window/window.c \
	window/windowcmpt.c \
	window/window_cms.c \
	window/windowdata.c \
	window/windowdrop.c \
	window/window_get.c \
	window/windowlayt.c \
	window/window_set.c \
	window/windowutil.c \
	win/win_bell.c \
	win/win_cms.c \
	win/win_cntral.c \
	win/win_compat.c \
	win/win_cursor.c \
	win/win_damage.c \
	win/win_env.c \
	win/win_geom.c \
	win/win_getscr.c \
	win/win_global.c \
	win/win_input.c \
	win/win_keymap.c \
	win/win_treeop.c \
	win/win_ttyenv.c \
	wmgr/wmgr_decor.c \
	wmgr/wmgr_menu.c \
	wmgr/wmgr_rect.c \
	wmgr/wmgr_state.c \
	# keep this list sorted using : ls */*.c | sort

AM_CPPFLAGS = $(SYS_INCLUDES) -std=c89 -D_GNU_SOURCE -DX11R6
