# Copyright (C) 2026 olvwm.xview@gmail.com
# SPDX-License-Identifier: GPL-3.0-only

lib_LTLIBRARIES = libolgx.la libxview.la

# Install headers
olgxincludedir = $(includedir)/olgx
pixrectincludedir = $(includedir)/pixrect
xviewincludedir = $(includedir)/xview

dist_olgxinclude_HEADERS = libolgx/olgx.h
dist_xviewinclude_HEADERS = libxview/xview.h
