# Copyright (C) 2026 olvwm.xview@gmail.com
# SPDX-License-Identifier: GPL-3.0-only

include_xview_private_HEADERS = \
	charimage.h charscreen.h ttyansi.h tty_impl.h term_impl.h

include_xview_HEADERS = ttysw.h tty.h termsw.h

include_xview_privatedir = ${includedir}/xview_private
include_xviewdir = ${includedir}/xview
